
CREATE PROCEDURE RemoveAdsByStatus
@AdStatus int
AS
SET XACT_ABORT ON
SET NOCOUNT ON
BEGIN TRANSACTION
DELETE FROM Photos WHERE AdId IN (SELECT Id FROM Ads WHERE AdStatus = @AdStatus)
DELETE FROM SavedAds WHERE AdId IN (SELECT Id FROM Ads WHERE AdStatus = @AdStatus)
DELETE FROM Ads WHERE AdStatus = @AdStatus
COMMIT