{{- if .Values.secretProviderClass.create -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "time-tracker.fullname" . }}
spec:
  provider: {{ .Values.secretProviderClass.provider }}
  secretObjects:
    - secretName: {{ .Values.secretProviderClass.secretName }}
      type: Opaque
      data:
      - objectName: {{ .Values.secretProviderClass.secretName }}
        key: {{ .Values.secretProviderClass.secretName }}
  parameters:
    keyvaultName: {{ .Values.secretProviderClass.keyVaultName }}
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.secretProviderClass.userAssignedIdentityId }}
    cloudName: ""
    objects:   |
      array:
        - |
          objectName: {{ .Values.secretProviderClass.secretName }}
          objectType: secret
          objectVersion: ""
    tenantId: {{ .Values.secretProviderClass.tenantId }}
{{- end }}
