{{- if .Values.service.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "time-tracker.fullname" . }}
  labels:
    {{- include "time-tracker.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      # targetPort: http
      # protocol: TCP
      # name: http
  selector:
    {{- include "time-tracker.selectorLabels" . | nindent 4 }}
{{- end }}
