{{- if .Values.secretProviderClass.create -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "classifieds.fullname" . }}
spec:
  provider: {{ .Values.secretProviderClass.provider }}
  secretObjects:
    {{- range .Values.secretProviderClass.secretObjects }}
    - secretName: {{ .secretName }}
      type: Opaque
      data:
      - objectName: {{ .objectName }}
        key: {{ .secretName }}
    {{- end }}
  parameters:
    keyvaultName: {{ .Values.secretProviderClass.keyVaultName }}
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.secretProviderClass.userAssignedIdentityId }}
    cloudName: ""
    objects:   |
      array:
      {{- range .Values.secretProviderClass.secretObjects }}
        - |
          objectName: {{ .objectName }}
          objectType: secret
          objectVersion: ""
      {{- end }}
    tenantId: {{ .Values.secretProviderClass.tenantId }}
{{- end }}
